services:    
  db:
    volumes:
      - db_data_dev:/var/lib/postgresql/18/docker
  

  s3:
    volumes:
      - s3_data_dev:/data


  # Fake mail server, for development environment only
  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:1025:1025" # SMTP server
      - "127.0.0.1:8025:8025" # Web UI


  # Redis web UI for debug, for development environment only
  redis-insight:
      image: redis/redisinsight:latest
      restart: unless-stopped
      ports:
        - "127.0.0.1:${REDIS_INSIGHT_PORT:-5540}:5540"
      volumes:
        - redis-insight-data-dev:/data

  
volumes:
  db_data_dev:
  s3_data_dev:
  redis-insight-data-dev: