services:
  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend/:/app/
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT_EXTERNAL:-5173}:5173"

  # backend:
  #   build:
  #     context: ./backend
  #   ports:
  #     - "${BACKEND_PORT_EXTERNAL:-8080}:8080"
    
  db:
    volumes:
      - db_data_dev:/var/lib/postgresql/18/docker

  redis-insight:
      image: redis/redisinsight:latest
      restart: unless-stopped
      ports:
        - "5540:5540"
      volumes:
        - redis-insight-data:/data

  s3:
    volumes:
      - s3_data_dev:/data
    ports:
      - "127.0.0.1:9001:9001"
      - "127.0.0.1:9000:9000"
volumes:
  db_data_dev:
  s3_data_dev:
  redis-insight-data: