# -----------------------------------------------------------
#           PRODUCTION PROFILE
# -----------------------------------------------------------

springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

s3.endpoint=${S3_ENDPOINT}
s3.access-key=${S3_ACCESS_KEY}
s3.secret-key=${S3_SECRET_KEY}
s3.region=${S3_REGION}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

jwt.secret-key=${JWT_SECRET_KEY}
jwt.access-token-expiration-second=
jwt.refresh-token-expiration-second=
jwt.access-token-cookie-name=${JWT_ACCESS_COOKIE_NAME:access_token}
jwt.refresh-token-cookie-name=${JWT_REFRESH_COOKIE_NAME:refresh_token}

logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_SEND_FROM}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true