spring.profiles.active=dev

spring.application.name=mindcard

# Increase max upload size for audio and images
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
