# -----------------------------------------------------------
#           DEVELOPMENT PROFILE
# -----------------------------------------------------------

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/mindcard
spring.datasource.username=user
spring.datasource.password=changethis
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

s3.endpoint=http://localhost:9001
s3.access-key=user
s3.secret-key=password
s3.region=ap-southeast-1

spring.data.redis.host=localhost
spring.data.redis.port=6379

jwt.secret-key=rfgjhjlqwrhkjfhkjfhkjafhkjsdhfkjsdhfsfkasdadadasdadasdasdadasdadasdasdas
jwt.access-token-expiration-second=300
jwt.refresh-token-expiration-second=604800
jwt.access-token-cookie-name=access_token
jwt.refresh-token-cookie-name=refresh_token

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=mindcard@mail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true