# -----------------------------------------------------------
#           DEVELOPMENT PROFILE
# -----------------------------------------------------------

springdoc.default-produces-media-type=application/json
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.default-flat-param-object=true

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mindcard}
spring.datasource.username=${DB_USER:user}
spring.datasource.password=${DB_PASSWORD:changethis}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

s3.endpoint=${S3_ENDPOINT:http://s3:9000}
s3.public-url-override=${S3_PUBLIC_URL_OVERRIDE:http://localhost:9000}
s3.access-key=${S3_ACCESS_KEY:admin}
s3.secret-key=${S3_SECRET_KEY:changethis}
s3.region=${S3_REGION:ap-southeast-1}
s3.default-bucket=${S3_BUCKET:mindcard}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

jwt.secret-key=changethis_123456789iwfvbddzfduawiurbc87235683297456314
jwt.access-token-expiration-second=${JWT_ACCESS_TOKEN_EXPIRATION_SECOND:1800}
jwt.refresh-token-expiration-second=${JWT_REFRESH_TOKEN_EXPIRATION_SECOND:604800}
jwt.access-token-cookie-name=${JWT_ACCESS_COOKIE_NAME:access_token}
jwt.refresh-token-cookie-name=${JWT_REFRESH_COOKIE_NAME:refresh_token}

spring.mail.host=${MAIL_HOST:localhost}
spring.mail.port=${MAIL_PORT:1025}
spring.mail.username=${MAIL_SEND_FROM:mindcard@fakemail.com}
spring.mail.password=${MAIL_PASSWORD:changethis}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true