spring.application.name=mindcard
springdoc.swagger-ui.path=/docs
springdoc.aoi-docs.path=/api-docs

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mindcard}
spring.datasource.username=${DB_USER:user}
spring.datasource.password=${DB_PASSWORD:changethis}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}